apiVersion: v1
kind: Secret
metadata:
  name: color-palette-secrets
  namespace: color-palette-api
type: Opaque
stringData:
  metricsToken: "<GENERATE_RANDOM_TOKEN>" # NOTE: Placeholder for demo you gotta use ExternalSecrets in production.

