apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: color-palette-api

resources:
  - ../../base/namespace.yaml
  - ../../base/deployment.yaml
  - ../../base/service.yaml
  - ../../base/configmap.yaml
  - ../../base/secrets.yaml
  #- ../../base/hpa.yaml  # we are not using hpa for this one but you can uncomment if needed

images:
  - name: <ECR_REPO_URI>
    newName: 980664882691.dkr.ecr.us-east-1.amazonaws.com/sample-app
    newTag:  sample-app
